apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-v2-service
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app-v2
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000